services:
  - type: web
    name: respiria-ml-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RESPIRIA_BACKEND_URL
        value: https://respira-backend.onrender.com/api/v1
      - key: DEBUG
        value: "False"
      - key: FLASK_ENV
        value: production
